#!/bin/bash
set -ue

[ -z "$EDITOR" ] && EDITOR="vi"

newpost() {
        filecount=$(ls "authors" | wc -l)
        [ $filecount -eq 0 ] && { echo "There are no authors." ; exit 1 ; }
        read -erp "Title: " title
        echo "$title" | grep \" >/dev/null && echo "Use unicode quotes in titles." && exit 1
        url="$(echo "$title" | iconv -f UTF-8 -t ASCII//TRANSLIT | tr -d '[:punct:]' | tr '[:upper:]' '[:lower:]' | tr ' ' '-' | sed -E 's/-+/-/g' | sed 's/\(^-\|-$\)//g')"
        [ -f "zerm/$url.md" ] && echo "There is already an article with the same name/URL." && exit 1
        echo "$url,\"$title\"" >> drafts.csv
        touch "zerm/$url.md"
        $EDITOR "zerm/$url.md"
}

getDraftTo() {
        files="$(cut -d, -f1 drafts.csv)"
        filecount=$(wc -l drafts.csv | awk '{ print $1 }')
        [ $filecount -eq 0 ] && echo "There's nothing to $1." && exit 1
        number=1
        [ $filecount -ne 1 ] && {
                echo "$files" | nl
                read -erp "Pick an entry by number to $1, or press Ctrl-C to cancel. " number
        }
        SELECTION="$(echo "$files" | nl | grep -w "$number" | awk '{ print $2 }')"
}

publish() {
        id=$(tail -n 1 articles.csv | rev | cut -d, -f1 | rev)
        id=$(($id + 1))
        read -erp "Author ($(ls authors | tr '\n' ' ' | sed 's/\.html /, /g; s/, $//')): " author
        read -erp "Published (\"dd.mm.yy hh:mm:ss CES?T\") [now]: " pub
        [ "$pub" = "" -o "$pub" = "now" ] && pub="$(date '+%d.%m.%Y %H:%M:%S %Z')"
        title="$(grep "^$1," drafts.csv | cut -d, -f2-)"
        echo "$pub,$1,$title,$author,$id" >> articles.csv
        # TODO: fix crash here because grep returns 1
        grep -v "^$1," drafts.csv > tmp
        mv -f tmp drafts.csv
        read -erp "Commit? [y/N] " commit
        [ "$commit" = "y" ] && git add -A && git commit -m "Published $title."
}

zerm2pdf() {
        [ "$1" = "" ] && echo "Usage: zm PDF [year]" && exit 1
        ! grep "^$1," gas.csv >/dev/null && echo 'Year does not exist.' && exit 2

        ids="$(grep "^$1," gas.csv | cut -d, -f2)"

        for id in $ids ; do
                /bin/echo -n "# "
                grep ",$id$" articles.csv | cut -d, -f3- | rev | cut -d, -f3- | rev | sed 's/^"//;s/"$//'
                perl -pe 's|\\{.*?\\}||g' "zerm/$(grep ",$id$" articles.csv | cut -d, -f2).md" \
                        | sed -E 's/ +,/,/g;s/ +/ /g'
        done | cat -s | pandoc --pdf-engine=xelatex -o "$1.pdf"
}

case "$1" in
        n*) newpost ;;
        e*) getDraftTo edit && $EDITOR "zerm/$SELECTION.md" ;;
        p*) getDraftTo publish && publish "$SELECTION" ;;
        P*) zerm2pdf $2 ;;
        *) echo "zm2 by ZERM <zerm@chrissx.de>

Usage:
$0 n[ew]
$0 e[dit]
$0 p[ublish]
$0 P[DF]

See https://github.com/ZERMZeitung/zm2 for more." ;;
esac
