#!/bin/bash

[ -z "$EDITOR" ] && EDITOR="vi"

newpost() {
        filecount=$(ls "authors" | wc -l)
        [ $filecount -eq 0 ] && { echo "There are no authors." ; exit 1 ; }
        read -erp "Title: " title
        echo "$title" | grep \" >/dev/null && echo "Use unicode quotes in titles." && exit 1
        url="$(echo "$title" | iconv -f UTF-8 -t ASCII//TRANSLIT | tr -d '[:punct:]' | tr '[:upper:]' '[:lower:]' | tr ' ' '-' | sed -E 's/-+/-/g' | sed 's/\(^-\|-$\)//g')"
        [ -f "zerm/$url.md" ] && echo "There is already an article with the same name/URL." && exit 1
        echo "$url,\"$title\"," >> drafts.csv
        touch "zerm/$url.md"
        $EDITOR "zerm/$url.md"
}

getDraftTo() {
        files="$(cut -d, -f1 drafts.csv)"
        filecount=$(echo "$files" | wc -l)
        [ $filecount -eq 0 ] && echo "There's nothing to $1." && exit 1
        number=1
        [ $filecount -ne 1 ] && {
                echo "$files" | nl
                read -erp "Pick an entry by number to $1, or press Ctrl-C to cancel. " number
        }
        echo "$files" | nl | grep -w "$number" | awk '{ print $2 }'
}

publish() {
        id=0
        while grep ",$id$" articles.csv >/dev/null ; do
                id=$(($id + 1))
        done
        # TODO: put selection here again
        read -erp "Author: " author
        read -erp "Published (\"dd.mm.yy hh:mm:ss CES?T\") [now]: " pub
        [ "$pub" = "" -o "$pub" = "now" ] && pub="$(date '+%d.%m.%Y %H:%M:%S %Z')"
        title="$(grep "^$1," drafts.csv | cut -d, -f2-)"
        echo "$pub,$1,$title,$author,$id" >> articles.csv
        grep -v "^$1," drafts.csv > tmp
        mv -f tmp drafts.csv
        echo "Article published!"
}

case "$1" in
        n*) newpost ;;
        e*) $EDITOR "zerm/$(getDraftTo edit).md" ;;
        p*) publish "$(getDraftTo publish)" ;;
        *) echo "zm2 by ZERM <zerm@chrissx.de>
Usage:
zm n: new draft
zm e: edit draft
zm p: publish draft

See https://github.com/ZERMZeitung/zm2 for more." ;;
esac
